name: CI

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        npm install
        npm run build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3.3.5
      with:
        GITHUB_TOKEN: ${{ secrets.personal_access_token }}
        BRANCH: gh-pages
        FOLDER: dist
